INSERT INTO expenses VALUES('23-Sep-15','Amazon','1','Points','-2.63','Refund');
INSERT INTO expenses VALUES('15-Jul-11','Cambridge Bicycle','1','Bianchi Volpe 53cm','1099','Bicycle');
INSERT INTO expenses VALUES('15-Jul-11','Cambridge Bicycle','1','Mavic Pulse Black (Shoes)','89.96','Clothing');
INSERT INTO expenses VALUES('15-Jul-11','Cambridge Bicycle','1','MA Tax','88.98','Tax');
INSERT INTO expenses VALUES('15-Jul-11','Cambridge Bicycle','1','Shimano PD-M520','58.46','Parts');
INSERT INTO expenses VALUES('15-Jul-11','Cambridge Bicycle','2','Sereas Seca Tire w/fps 700x28 wire bead','45','Parts');
INSERT INTO expenses VALUES('15-Jul-11','Cambridge Bicycle','1','Zefal Discovery Rack','40.46','Accessories');
INSERT INTO expenses VALUES('15-Jul-11','Cambridge Bicycle','1','Planet Bike Hardcore Fenders','35.96','Accessories');
INSERT INTO expenses VALUES('15-Jul-11','Cambridge Bicycle','1','Planet Bike Blinky Tail Light','25.16','Accessories');
INSERT INTO expenses VALUES('15-Jul-11','Cambridge Bicycle','3','700 x  25-30 32mm tubes','16.2','Parts');
INSERT INTO expenses VALUES('15-Jul-11','Cambridge Bicycle','2','Pedro''s Tire Levers','4.5','Tools');
INSERT INTO expenses VALUES('15-Jul-11','Cambridge Bicycle','1','Planet Bike Tail Light Rack Mount Bracket ','4.46','Accessories');
INSERT INTO expenses VALUES('15-Jul-11','Cambridge Bicycle','1','Sunlite Bottle Cage','4.46','Accessories');
INSERT INTO expenses VALUES('16-Jul-11','Amazon','1','ABUS U-lock','61.98','Accessories');
INSERT INTO expenses VALUES('16-Jul-11','Amazon','1','Pearl Izumi Attack Shorts','51.45','Clothing');
INSERT INTO expenses VALUES('16-Jul-11','Amazon','1','Pearl Izumi Fingerless Gloves','18.69','Clothing');
INSERT INTO expenses VALUES('21-Jul-11','Amazon','1','Pearl Izumi Quest Jersey','36.9','Clothing');
INSERT INTO expenses VALUES('21-Jul-11','Amazon','1','Shipping','7.98','Shipping');
INSERT INTO expenses VALUES('21-Jul-11','Amazon','1','CamelBak Podium Bottle','7.72','Accessories');
INSERT INTO expenses VALUES('22-Sep-11','Cambridge Bicycle','1','Planet Bike Blaze 1-Watt LED','44.95','Accessories');
INSERT INTO expenses VALUES('22-Sep-11','Cambridge Bicycle','1','MA Tax','2.81','Tax');
INSERT INTO expenses VALUES('2-Oct-11','Amazon','1','Sugoi Resistor Booties','41.18','Clothing');
INSERT INTO expenses VALUES('2-Oct-11','Amazon','1','Sigma BC1609 Bike Computer','33.52','Accessories');
INSERT INTO expenses VALUES('2-Oct-11','Amazon','1','Super Saver Discount','-1.37','Refund');
INSERT INTO expenses VALUES('2-Oct-11','Amazon','1','Super Saver Discount','-4.16','Refund');
INSERT INTO expenses VALUES('4-Oct-11','Bike Nashbar','1','Panniers','39.99','Accessories');
INSERT INTO expenses VALUES('4-Oct-11','Bike Nashbar','1','Shipping','6.99','Shipping');
INSERT INTO expenses VALUES('23-Oct-11','Amazon','1','Pearl Izumi Amphib Tights','97.46','Clothing');
INSERT INTO expenses VALUES('23-Oct-11','Amazon','1','Planet Bike Blinky Light Set','14.99','Accessories');
INSERT INTO expenses VALUES('30-Oct-11','Belmont Wheelworks','1','Gore Bike Wear Tool SO Jacket','200','Clothing');
INSERT INTO expenses VALUES('30-Oct-11','Belmont Wheelworks','1','Pearl Izumi Lobster Claws','75','Clothing');
INSERT INTO expenses VALUES('30-Oct-11','Belmont Wheelworks','1','Pearl Izumi Thermal Leg Warmers','45','Clothing');
INSERT INTO expenses VALUES('16-Nov-11','Belmont Wheelworks','1','Showers Pass Double Century','125','Clothing');
INSERT INTO expenses VALUES('16-Nov-11','Belmont Wheelworks','1','Slim Band Pants Straps','5.75','Accessories');
INSERT INTO expenses VALUES('30-Nov-11','Amazon','1','Serfas TSL-250 True Light','74.92','Accessories');
INSERT INTO expenses VALUES('8-Dec-11','En Route','1','Ground Score','-2','Refund');
INSERT INTO expenses VALUES('13-Dec-11','Cambridge Bicycle','1','Aquilo Gloves Xlarge','34.95','Clothing');
INSERT INTO expenses VALUES('13-Dec-11','Cambridge Bicycle','1','Merino Wool Socks','15','Clothing');
INSERT INTO expenses VALUES('13-Dec-11','Cambridge Bicycle','1','MA Tax','3.12','Tax');
INSERT INTO expenses VALUES('19-Dec-11','Cambridge Bicycle','2','700 x  25-30 32mm tubes','12','Parts');
INSERT INTO expenses VALUES('19-Dec-11','Cambridge Bicycle','1','MA Tax','0.75','Tax');
INSERT INTO expenses VALUES('2-Jan-12','Sears','1','Safety Glasses','7.99','Clothing');
INSERT INTO expenses VALUES('2-Jan-12','Sears','1','MA Tax','0.5','Tax');
INSERT INTO expenses VALUES('3-Jan-12','Cambridge Bicycle','1','Wigwam 67% Merino Socks','17.95','Clothing');
INSERT INTO expenses VALUES('3-Jan-12','Cambridge Bicycle','1','MA Tax','1.12','Tax');
INSERT INTO expenses VALUES('19-Jan-12','Brookline Lock Co','1','Bugngee 3-pack','1','Accessories');
INSERT INTO expenses VALUES('19-Jan-12','Brookline Lock Co','1','MA Tax','0.05','Tax');
INSERT INTO expenses VALUES('3-Feb-12','Cambridge Bicycle','1','Delta Bungee Net','9.95','Accessories');
INSERT INTO expenses VALUES('3-Feb-12','Cambridge Bicycle','1','CamelBak Podium Bottle','8.95','Accessories');
INSERT INTO expenses VALUES('3-Feb-12','Cambridge Bicycle','1','Sunlite Bottle Cage','4.95','Accessories');
INSERT INTO expenses VALUES('8-Feb-12','Cambridge Bicycle','2','700 x  25-30 32mm tubes','12','Parts');
INSERT INTO expenses VALUES('8-Feb-12','Cambridge Bicycle','1','MA Tax','0.75','Tax');
INSERT INTO expenses VALUES('14-Feb-12','Arkel','1','Commuter Pannier','149','Accessories');
INSERT INTO expenses VALUES('14-Feb-12','Arkel','1','Shipping','6.85','Shipping');
INSERT INTO expenses VALUES('16-Feb-12','Cambridge Bicycle','1','Park Tool VP-1 Patch Kit','4.95','Parts');
INSERT INTO expenses VALUES('16-Feb-12','Cambridge Bicycle','1','MA Tax','0.31','Tax');
INSERT INTO expenses VALUES('20-Feb-12','Cambridge Bicycle','1','SRAM 9-Speed PG-950 Rd Cassette 11-26','39.95','Parts');
INSERT INTO expenses VALUES('20-Feb-12','Cambridge Bicycle','1','Kool Stop V-Brake Pad Inserts','11.95','Parts');
INSERT INTO expenses VALUES('20-Feb-12','Cambridge Bicycle','1','Labor: Replace Cassette w/Tune Up','8','Labor');
INSERT INTO expenses VALUES('20-Feb-12','Cambridge Bicycle','1','Labor: Replace Chain w/Tune Up','8','Labor');
INSERT INTO expenses VALUES('20-Feb-12','Cambridge Bicycle','1','Labor: Basic Flat Fix','7.99','Labor');
INSERT INTO expenses VALUES('20-Feb-12','Cambridge Bicycle','1','700 x  28-35 48mm tubes','6','Parts');
INSERT INTO expenses VALUES('20-Feb-12','Cambridge Bicycle','1','MA Tax','3.62','Tax');
INSERT INTO expenses VALUES('7-Apr-12','Amazon','1','Park Tool CG-2 Chain Gang Chain Cleaning System','26.8','Tools');
INSERT INTO expenses VALUES('19-Apr-12','Ferris Wheels','1','Chain Tool','12.92','Tools');
INSERT INTO expenses VALUES('19-Apr-12','Cambridge Bicycle','1','Missing Link','5','Parts');
INSERT INTO expenses VALUES('19-Apr-12','Ferris Wheels','1','Missing Link','3.99','Parts');
INSERT INTO expenses VALUES('19-Apr-12','Cambridge Bicycle','1','Presta Pump Adaptor','2.95','Tools');
INSERT INTO expenses VALUES('19-Apr-12','Ferris Wheels','1','MA Tax','1.03','Tax');
INSERT INTO expenses VALUES('6-May-12','Belmont Wheelworks','1','Arkel Pannier Rain Cover','19.99','Accessories');
INSERT INTO expenses VALUES('6-May-12','Belmont Wheelworks','1','MA Tax','1.25','Tax');
INSERT INTO expenses VALUES('15-May-12','Cambridge Bicycle','1','700 x  28-35 32mm tubes','6','Parts');
INSERT INTO expenses VALUES('15-May-12','Cambridge Bicycle','1','Park Tool VP-1 Patch Kit','4.95','Parts');
INSERT INTO expenses VALUES('15-May-12','Cambridge Bicycle','1','Velox Rim Tape - Medium','4.95','Parts');
INSERT INTO expenses VALUES('15-May-12','Cambridge Bicycle','1','MA Tax','0.99','Tax');
INSERT INTO expenses VALUES('18-May-12','Cambridge Bicycle','1','Cable Hanger','7','Parts');
INSERT INTO expenses VALUES('18-May-12','Cambridge Bicycle','1','Cable Housing','2','Parts');
INSERT INTO expenses VALUES('18-May-12','Cambridge Bicycle','1','MA Tax','0.56','Tax');
INSERT INTO expenses VALUES('6-Jun-12','Belmont Wheelworks','1','Seat Bag','17.99','Accessories');
INSERT INTO expenses VALUES('6-Jun-12','Belmont Wheelworks','2','Park Cone Wrench 13mm','16.18','Tools');
INSERT INTO expenses VALUES('6-Jun-12','Belmont Wheelworks','1','Bike Peddlar Eyeglass Rearview Mirror','13.49','Accessories');
INSERT INTO expenses VALUES('6-Jun-12','Belmont Wheelworks','1','Boesheild T-9 Chain Lube','10.79','Parts');
INSERT INTO expenses VALUES('6-Jun-12','Belmont Wheelworks','1','Park Spoke Wrench','8.99','Tools');
INSERT INTO expenses VALUES('6-Jun-12','Belmont Wheelworks','1','MA Tax','4.22','Tax');
INSERT INTO expenses VALUES('8-Jun-12','Amazon','2','Park Cone Wrench 15mm','17.78','Tools');
INSERT INTO expenses VALUES('12-Jun-12','Cambridge Bicycle','2','Park Cone Wrench 17mm','19.9','Tools');
INSERT INTO expenses VALUES('12-Jun-12','Cambridge Bicycle','1','MA Tax','1.24','Tax');
INSERT INTO expenses VALUES('13-Jun-12','Harris Cyclery','2','Continental Gatorskin 700x23','85.9','Parts');
INSERT INTO expenses VALUES('13-Jun-12','Harris Cyclery','4','Giant Innertube 700x23-25C/27x1','23.8','Parts');
INSERT INTO expenses VALUES('13-Jun-12','Harris Cyclery','1','MA Tax','6.86','Tax');
INSERT INTO expenses VALUES('26-Jun-12','Cambridge Bicycle','1','Tiagra Cones & Bearings','20','Parts');
INSERT INTO expenses VALUES('26-Jun-12','Cambridge Bicycle','1','MA Tax','1.25','Tax');
INSERT INTO expenses VALUES('1-Jul-12','Red Jersey Cyclery','1','SRAM Deraileur Cable','6','Parts');
INSERT INTO expenses VALUES('2-Jul-12','Home Depot','1','3/4" Black Floor Flange','4.47','Tools');
INSERT INTO expenses VALUES('2-Jul-12','Home Depot','2','3/4" 90 Black Elbow','3.32','Tools');
INSERT INTO expenses VALUES('2-Jul-12','Home Depot','2','3/4" Black Cap','3.2','Tools');
INSERT INTO expenses VALUES('2-Jul-12','Home Depot','1','MA Tax','0.69','Tax');
INSERT INTO expenses VALUES('4-Jul-12','Home Depot','1','3/4" 24" Black Nipple','7.24','Tools');
INSERT INTO expenses VALUES('4-Jul-12','Home Depot','1','3/4" Black Floor Flange','4.47','Tools');
INSERT INTO expenses VALUES('4-Jul-12','Home Depot','1','3/4" 90 Black Elbow','1.66','Tools');
INSERT INTO expenses VALUES('4-Jul-12','Home Depot','1','MA Tax','0.84','Tax');
INSERT INTO expenses VALUES('5-Jul-12','Home Depot','1','3/4" 12" Black Nipple','5.45','Tools');
INSERT INTO expenses VALUES('5-Jul-12','Home Depot','1','MA Tax','0.34','Tax');
INSERT INTO expenses VALUES('6-Aug-12','Amazon','1','Halo II Headband','10.17','Clothing');
INSERT INTO expenses VALUES('27-Aug-12','Cambridge Bicycle','1','SRAM 9-Speed PG-950 Rd Cassette 11-26','39.95','Parts');
INSERT INTO expenses VALUES('27-Aug-12','Cambridge Bicycle','1','SRAM PC951 9-Speed Chain','24.95','Parts');
INSERT INTO expenses VALUES('27-Aug-12','Cambridge Bicycle','1','Park Tool SR-1 Chain Whip','24.95','Tools');
INSERT INTO expenses VALUES('27-Aug-12','Cambridge Bicycle','1','Park Tool FR-5C Shimano HG Tool','6.95','Tools');
INSERT INTO expenses VALUES('27-Aug-12','Cambridge Bicycle','1','MA Tax','6.05','Tax');
INSERT INTO expenses VALUES('7-Sep-12','Harris Cyclery','1','Sugino 110mm 52T Chainring Silver','54.95','Parts');
INSERT INTO expenses VALUES('7-Oct-12','Amazon','1','ARKON CMP227 Motorcycle and Bicycle Handle Bar Mount for Cameras with 1/4 20 Screw Thread','6.37','Accessories');
INSERT INTO expenses VALUES('16-Oct-12','Amazon','1','J Fit 36-Inch Super High-Density Foam Roller','23.5','Tools');
INSERT INTO expenses VALUES('19-Oct-12','Amazon','1','American Weigh SR-20 Yellow Digital Hanging Scale, 44lb by 0.02lb','12.81','Tools');
INSERT INTO expenses VALUES('5-Nov-12','Cambridge Bicycle','1','Gore Helmet Cap, Black, Medium','32.95','Clothing');
INSERT INTO expenses VALUES('5-Nov-12','Cambridge Bicycle','1','MA Tax','2.06','Tax');
INSERT INTO expenses VALUES('4-Jan-13','Cambridge Bicycle','1','Finish Line Citrus Degreaser','11.95','Parts');
INSERT INTO expenses VALUES('4-Jan-13','Cambridge Bicycle','1','MA Tax','0.75','Tax');
INSERT INTO expenses VALUES('23-Jan-13','Belmont Wheelworks','1','Lake ATB MXZ302 Black 45','280','Clothing');
INSERT INTO expenses VALUES('23-Jan-13','Belmont Wheelworks','1','MA Tax','17.5','Tax');
INSERT INTO expenses VALUES('24-Jan-13','Ferris Wheels','1','GA MERSEAS SOCKS','19.9','Clothing');
INSERT INTO expenses VALUES('24-Jan-13','Ferris Wheels','2','Charcoal Toe Warmers','6.3','Clothing');
INSERT INTO expenses VALUES('24-Jan-13','Ferris Wheels','1','MA Tax','0.33','Tax');
INSERT INTO expenses VALUES('28-Jan-13','Cambridge Bicycle','1','Shimano SM-SH56 Multi-Release SPD Cleats','24.95','Clothing');
INSERT INTO expenses VALUES('28-Jan-13','Cambridge Bicycle','1','MA Tax','1.56','Tax');
INSERT INTO expenses VALUES('1-Feb-13','Sara Bresnick','1','Bike Fit','150','Labor');
INSERT INTO expenses VALUES('6-Feb-13','Cambridge Bicycle','2','Road Bike Cables','5.9','Parts');
INSERT INTO expenses VALUES('6-Feb-13','Cambridge Bicycle','1','MA Tax','0.37','Tax');
INSERT INTO expenses VALUES('25-Mar-13','Economy Hardware','1','Energizer 3v Lith 2032 Battery','6.49','Parts');
INSERT INTO expenses VALUES('25-Mar-13','Economy Hardware','1','MA Tax','0.81','Tax');
INSERT INTO expenses VALUES('22-Apr-13','Cambridge Bicycle','1','Cambridge Bicycle Logo Pace Hat','14.95','Clothing');
INSERT INTO expenses VALUES('22-Apr-13','Dedham Bike','1','Bontrager Standard Tube 700x23','7.99','Parts');
INSERT INTO expenses VALUES('22-Apr-13','Dedham Bike','1','Action Patch Kit, Small','4.99','Parts');
INSERT INTO expenses VALUES('22-Apr-13','Cambridge Bicycle','1','MA Tax','0.93','Tax');
INSERT INTO expenses VALUES('22-Apr-13','Dedham Bike','1','MA Tax','0.81','Tax');
INSERT INTO expenses VALUES('4-May-13','Amazon','1','Pearl iZUMi Attack Sock 3-Pack,Black,X-Large','18','Clothing');
INSERT INTO expenses VALUES('19-May-13','Wahoo Fitness','1','Wahoo Fitness - Wahoo RFLKT iPhone Powered Bike Computer','129.99','Accessories');
INSERT INTO expenses VALUES('19-May-13','Amazon','1','Wahoo Fitness Blue HR Heart Rate Strap for iPod/iPhone','69.99','Accessories');
INSERT INTO expenses VALUES('19-May-13','Amazon','1','Wahoo Fitness Blue SC Cycling Speed & Cadence Sensor for iPod/iPhone','59.99','Accessories');
INSERT INTO expenses VALUES('19-May-13','Advance Auto Parts','2','Citrus Degreaser Spray','7','Parts');
INSERT INTO expenses VALUES('19-May-13','Landry''s Bicycles','1','Stainless Shift Cable, 2300mm','5','Parts');
INSERT INTO expenses VALUES('19-May-13','Advance Auto Parts','1','MA Tax','0.44','Tax');
INSERT INTO expenses VALUES('19-May-13','Landry''s Bicycles','1','MA Tax','0.31','Tax');
INSERT INTO expenses VALUES('23-May-13','Cambridge Bicycle','1','700c Open Sport Rear Wheel w/Tiagra 4600 Hub','120','Parts');
INSERT INTO expenses VALUES('23-May-13','Cambridge Bicycle','1','Wheel Swap','15','Labor');
INSERT INTO expenses VALUES('23-May-13','Cambridge Bicycle','1','MA Tax','7.5','Tax');
INSERT INTO expenses VALUES('2-Jun-13','Amazon','1','Crank Brothers Multi Bicycle Tool 17','19.87','Tools');
INSERT INTO expenses VALUES('24-Jun-13','Belmont Wheelworks','1','Castelli Velocissimo Due Black XL Shorts','110','Clothing');
INSERT INTO expenses VALUES('12-Jul-13','Cambridge Bicycle','1','Serfas RX Glove Gel Lite XL Black','25.2','Clothing');
INSERT INTO expenses VALUES('12-Jul-13','Cambridge Bicycle','1','Brake Pad K/S Dura2 Salmon','21.52','Parts');
INSERT INTO expenses VALUES('12-Jul-13','Cambridge Bicycle','1','Chain-L Lube','10.76','Parts');
INSERT INTO expenses VALUES('12-Jul-13','Cambridge Bicycle','1','Giordana Trade Sock Mid Cuff Black/Flourescent L/XL','9','Clothing');
INSERT INTO expenses VALUES('12-Jul-13','Cambridge Bicycle','1','CamelBak Podium Bottle','8.06','Accessories');
INSERT INTO expenses VALUES('12-Jul-13','Cambridge Bicycle','1','700 x 18-23 48mm PV Tube','5.4','Parts');
INSERT INTO expenses VALUES('12-Jul-13','Cambridge Bicycle','1','MA Tax','5.38','Tax');
INSERT INTO expenses VALUES('12-Jul-13','Cambridge Bicycle','1','Clark''s Universal SIS Cable and Housing','5.36','Parts');
INSERT INTO expenses VALUES('12-Jul-13','Cambridge Bicycle','1','Clark''s Universal SIS Cable and Housing','5.36','Parts');
INSERT INTO expenses VALUES('12-Jul-13','Cambridge Bicycle','1','Park Tool VP-1 Patch Kit','4.46','Parts');
INSERT INTO expenses VALUES('16-Jul-13','Landry''s Bicycles','1','Specialized Air Tool CPR02 Trigger Inflator','25','Tools');
INSERT INTO expenses VALUES('16-Jul-13','Landry''s Bicycles','2','Shimano XTR M70R2 VBrake Pads Sev Cond INserts','23.98','Parts');
INSERT INTO expenses VALUES('16-Jul-13','Landry''s Bicycles','2','Gen. Innov.  C02 Cartridge 20g','12','Parts');
INSERT INTO expenses VALUES('16-Jul-13','Landry''s Bicycles','1','MA Tax','3.81','Tax');
INSERT INTO expenses VALUES('28-Jul-13','Landry''s Bicycles','1','Stainless Shift Cable, 2300mm','5','Parts');
INSERT INTO expenses VALUES('28-Jul-13','Landry''s Bicycles','1','MA Tax','0.31','Tax');
INSERT INTO expenses VALUES('6-Aug-13','Amazon','1','McNett Iron Mend Repair Kit, Black','9.89','Parts');
INSERT INTO expenses VALUES('7-Aug-13','Economy Hardware','1','Velcro Strap','4.49','Accessories');
INSERT INTO expenses VALUES('7-Aug-13','Economy Hardware','1','MA Tax','0.28','Tax');
INSERT INTO expenses VALUES('13-Aug-13','Cambridge Bicycle','2','Continental Gatorskin 700x23','99.9','Parts');
INSERT INTO expenses VALUES('13-Aug-13','Cambridge Bicycle','2','Sunlite 700 x 18-23 32mm PV Tube','12','Parts');
INSERT INTO expenses VALUES('13-Aug-13','Cambridge Bicycle','1','MA Tax','6.24','Tax');
INSERT INTO expenses VALUES('13-Aug-13','Cambridge Bicycle','1','Clark''s Universal SIS Cable and Housing','5.95','Parts');
INSERT INTO expenses VALUES('13-Aug-13','Cambridge Bicycle','1','MA Tax','0.75','Tax');
INSERT INTO expenses VALUES('13-Aug-13','Cambridge Bicycle','1','MA Tax','0.37','Tax');
INSERT INTO expenses VALUES('13-Aug-13','Cambridge Bicycle','1','MA Tax','-1.35','Refund');
INSERT INTO expenses VALUES('13-Aug-13','Cambridge Bicycle','1','Brake Pad K/S Dura2 Salmon','-21.52','Refund');
INSERT INTO expenses VALUES('19-Aug-13','Broadway Bicycle School','1','Pedro''s Cable Cutter','35','Tools');
INSERT INTO expenses VALUES('19-Aug-13','Broadway Bicycle School','1','Pedro''s Cable Puller','30','Tools');
INSERT INTO expenses VALUES('19-Aug-13','Broadway Bicycle School','1','Planet Bike C02 16g Refill 3-pack','12','Parts');
INSERT INTO expenses VALUES('19-Aug-13','Broadway Bicycle School','1','MA Tax','4.81','Tax');
INSERT INTO expenses VALUES('31-Aug-13','Norwood Bicycle Depot','1','Shimano HG73 9-Spd Chain','21','Parts');
INSERT INTO expenses VALUES('31-Aug-13','Norwood Bicycle Depot','1','Sunlite Patch Kit','10','Parts');
INSERT INTO expenses VALUES('31-Aug-13','Norwood Bicycle Depot','1','MA Tax','1.92','Tax');
INSERT INTO expenses VALUES('6-Sep-13','Landry''s Bicycles','4','Brake Cable Road','20','Parts');
INSERT INTO expenses VALUES('6-Sep-13','Landry''s Bicycles','4','Shift Cable 2300mm','20','Parts');
INSERT INTO expenses VALUES('6-Sep-13','Landry''s Bicycles','5','Shift Cable Housing SIS 5mm ','10','Parts');
INSERT INTO expenses VALUES('6-Sep-13','Landry''s Bicycles','6','Brake Cable Housing Black','9','Parts');
INSERT INTO expenses VALUES('6-Sep-13','Landry''s Bicycles','1','MA Tax','3.69','Tax');
INSERT INTO expenses VALUES('15-Sep-13','Amazon','1','Hanz All-Season Mid-Calf Waterproof Socks Lg','30.68','Clothing');
INSERT INTO expenses VALUES('15-Sep-13','Amazon','1','Save Our Soles Share the Road Socks, Neon Yellow, Large','9.95','Clothing');
INSERT INTO expenses VALUES('15-Sep-13','Amazon','1','Points','-30.68','Refund');
INSERT INTO expenses VALUES('15-Sep-13','Amazon','1','Points','-19.9','Refund');
INSERT INTO expenses VALUES('19-Sep-13','Belmont Wheelworks','1','Pearl Izumi Mens Elite Barrier Jacket','99','Clothing');
INSERT INTO expenses VALUES('19-Sep-13','REI','1','Sugoi Resistor Booties','24.83','Clothing');
INSERT INTO expenses VALUES('19-Sep-13','Belmont Wheelworks','1','Cream Pace Chamois Butter','13.49','Parts');
INSERT INTO expenses VALUES('19-Sep-13','REI','1','MA Tax','1.55','Tax');
INSERT INTO expenses VALUES('19-Sep-13','Belmont Wheelworks','1','MA Tax','0.84','Tax');
INSERT INTO expenses VALUES('2-Oct-13','Broadway Bicycle School','1','ALEXRIMS R450 6061H-T6 622x14 ','95','Parts');
INSERT INTO expenses VALUES('2-Oct-13','Broadway Bicycle School','1','Broadway Bicycle Repair Stand Rental','12','Tools');
INSERT INTO expenses VALUES('2-Oct-13','Broadway Bicycle School','1','Pedro''s Go Chain Lube','10','Parts');
INSERT INTO expenses VALUES('2-Oct-13','Broadway Bicycle School','1','MA Tax','5.88','Tax');
INSERT INTO expenses VALUES('2-Oct-13','Broadway Bicycle School','1','Plastic Rim Strip','5','Parts');
INSERT INTO expenses VALUES('10-Nov-13','Amazon','2','Energizer 2032 Battery CR2032 Lithium 3v (1 Pack of 5)','6.24','Accessories');
INSERT INTO expenses VALUES('11-Nov-13','Amazon','1','Shipping','4.54','Shipping');
INSERT INTO expenses VALUES('15-Nov-13','Amazon','1','Tacx Ball Bearing 9/10 Shimano Pulley Set','19.5','Parts');
INSERT INTO expenses VALUES('19-Nov-13','Broadway Bicycle School','1','Broadway Bicycle Repair Stand Rental','7','Tools');
INSERT INTO expenses VALUES('19-Nov-13','Broadway Bicycle School','1','Planet Bike C02 16g Refill short 3-pack (2)','5','Parts');
INSERT INTO expenses VALUES('19-Nov-13','Broadway Bicycle School','1','QTubes 700c x 18-23mm 48mm Presta','1','Parts');
INSERT INTO expenses VALUES('11-Dec-13','Cambridge Bicycle','1','Kool Stop V-Brake Pads','14.95','Parts');
INSERT INTO expenses VALUES('11-Dec-13','Cambridge Bicycle','1','MA Tax','0.93','Tax');
INSERT INTO expenses VALUES('8-Jan-14','Amazon','1','Energizer ECR2450 6 Batteries','8.9','Accessories');
INSERT INTO expenses VALUES('10-Apr-14','Cambridge Bicycle','2','Serfas 700x18-25 60mm PV Tube','13.98','Parts');
INSERT INTO expenses VALUES('10-Apr-14','Cambridge Bicycle','1','MA Tax','0.87','Tax');
INSERT INTO expenses VALUES('11-May-14','Landry''s Bicycles','1','CamelBak Podium Big Chill 25oz Bottle','15','Accessories');
INSERT INTO expenses VALUES('11-May-14','Landry''s Bicycles','1','MA Tax','0.94','Tax');
INSERT INTO expenses VALUES('14-May-14','Cambridge Bicycle','1','Innovations Threaded 16g CO2 2-pack','9.95','Parts');
INSERT INTO expenses VALUES('15-May-14','Rideye','1','FRONT & REAR_RIDEYE_32GB COMBO','305.99','Accessories');
INSERT INTO expenses VALUES('15-May-14','Rideye','1','Shipping','7.5','Shipping');
INSERT INTO expenses VALUES('27-May-14','Cambridge Bicycle','1','Serfas 700 x 18-25 60mm PV Tube','6.99','Parts');
INSERT INTO expenses VALUES('27-May-14','Cambridge Bicycle','1','MA Tax','0.44','Tax');
INSERT INTO expenses VALUES('2-Jun-14','Adi''s Bike World','1','Tube, CO2, Unknown','12.85','Parts');
INSERT INTO expenses VALUES('2-Jun-14','Adi''s Bike World','1','MA Tax','0.8','Tax');
INSERT INTO expenses VALUES('8-Jun-14','Amazon','1','Energizer 2032 Battery CR2032 Lithium 3v (1 Pack of 5)','3.15','Accessories');
INSERT INTO expenses VALUES('9-Jun-14','Amazon','1','Rema F0-P Round Patches, Box of 100, 16mm','18.99','Parts');
INSERT INTO expenses VALUES('9-Jun-14','Amazon','1','Sweat GUTR Sweatband - FROST','15.99','Clothing');
INSERT INTO expenses VALUES('9-Jun-14','Amazon','1','Patching Glue, Lot of 10','7.95','Parts');
INSERT INTO expenses VALUES('9-Jun-14','Amazon','1','Slime 1050 Rubber Cement - 8 oz.','7.62','Parts');
INSERT INTO expenses VALUES('9-Jun-14','Amazon','1','Shipping','1.98','Shipping');
INSERT INTO expenses VALUES('9-Jun-14','Amazon','1','Gift Card','-3.15','Refund');
INSERT INTO expenses VALUES('9-Jun-14','Amazon','1','Gift Card','-23.24','Refund');
INSERT INTO expenses VALUES('9-Jun-14','Amazon','1','Shipping','4.25','Shipping');
INSERT INTO expenses VALUES('9-Jun-14','Amazon','1','MA Tax','1','Tax');
INSERT INTO expenses VALUES('9-Jun-14','Amazon','1','Gift Card','-16.99','Refund');
INSERT INTO expenses VALUES('9-Jun-14','Amazon','1','Gift Card','-9.93','Refund');
INSERT INTO expenses VALUES('9-Jun-14','Amazon','1','MA Tax','0.48','Tax');
INSERT INTO expenses VALUES('9-Jun-14','Amazon','1','Gift Card','-8.1','Refund');
INSERT INTO expenses VALUES('14-Jun-14','Landry''s Bicycles','1','CamelBak Podium Bottle 25oz Insulated','15','Accessories');
INSERT INTO expenses VALUES('14-Jun-14','Landry''s Bicycles','2','Clif Shot Bloks','6','Parts');
INSERT INTO expenses VALUES('14-Jun-14','Landry''s Bicycles','1','Powerbar Gel Blast','1.99','Parts');
INSERT INTO expenses VALUES('14-Jun-14','Landry''s Bicycles','1','MA Tax','0.94','Tax');
INSERT INTO expenses VALUES('18-Jun-14','Ace Wheelworks','1','Various','94.27','Parts');
INSERT INTO expenses VALUES('18-Jun-14','Ace Wheelworks','1','C-Ring Shimano 5750 10S 50T','58.99','Parts');
INSERT INTO expenses VALUES('18-Jun-14','Ace Wheelworks','1','Bar Tape','19.99','Parts');
INSERT INTO expenses VALUES('18-Jun-14','Ace Wheelworks','1','MA Tax','10.83','Tax');
INSERT INTO expenses VALUES('3-Jul-14','Cambridge Bicycle','2','Pedro''s Tire Levers','3.5','Tools');
INSERT INTO expenses VALUES('3-Jul-14','Cambridge Bicycle','1','MA Tax','0.22','Tax');
INSERT INTO expenses VALUES('14-Jul-14','Cambridge Bicycle','1','UN-55 Bottom Bracket 68mm x 110mm','29.95','Parts');
INSERT INTO expenses VALUES('14-Jul-14','Cambridge Bicycle','1','Park Tool BBT-32 BB Tool for Shimano/Isis 20t Cup','11.95','Tools');
INSERT INTO expenses VALUES('14-Jul-14','Cambridge Bicycle','1','MA Tax','2.62','Tax');
INSERT INTO expenses VALUES('15-Jul-14','Cambridge Bicycle','1','Clark''s Stainless Shift Cable Housing','4.21','Parts');
INSERT INTO expenses VALUES('15-Jul-14','Cambridge Bicycle','1','Standard shift cable','2.55','Parts');
INSERT INTO expenses VALUES('15-Jul-14','Cambridge Bicycle','1','MA Tax','0.42','Tax');
INSERT INTO expenses VALUES('31-Jul-14','En Route','1','Ground Score','-1','Refund');
INSERT INTO expenses VALUES('6-Aug-14','Amazon','1','MA Tax','6.54','Tax');
INSERT INTO expenses VALUES('6-Aug-14','Amazon','1','Sta-Tru Silver Mavic Open Spor 32H Rim Rear Wheel (700X20)','104.56','Parts');
INSERT INTO expenses VALUES('6-Aug-14','Amazon','1','2 of Continental Grand Prix 4-Season Bicycle Tire (700x23, Wire Beaded, Black)','50.79','Parts');
INSERT INTO expenses VALUES('6-Aug-14','Cambridge Bicycle','1','Innovations Threaded 16g CO2 2-pack','9.95','Parts');
INSERT INTO expenses VALUES('6-Aug-14','Cambridge Bicycle','1','MA Tax','0.62','Tax');
INSERT INTO expenses VALUES('6-Aug-14','Amazon','1','MA Tax','6.34','Tax');
INSERT INTO expenses VALUES('17-Aug-14','Norwood Bicycle Depot','2','Brake Pad','17.18','Parts');
INSERT INTO expenses VALUES('17-Aug-14','Norwood Bicycle Depot','2','Rim Tape','10.7','Parts');
INSERT INTO expenses VALUES('20-Aug-14','Raised Knuckle Bicycle','1','CO2 Threaded 3-pk','9.99','Parts');
INSERT INTO expenses VALUES('20-Aug-14','Raised Knuckle Bicycle','1','700 x 18-23 PV Tube','7','Parts');
INSERT INTO expenses VALUES('20-Aug-14','Raised Knuckle Bicycle','1','Bulk Tire Lever','6.99','Tools');
INSERT INTO expenses VALUES('20-Aug-14','Raised Knuckle Bicycle','1','Kenda 700x23 32mm Tube','6.5','Parts');
INSERT INTO expenses VALUES('20-Aug-14','Raised Knuckle Bicycle','1','MA Tax','1.9','Tax');
INSERT INTO expenses VALUES('26-Aug-14','Amazon','1','Wheels Manufacturing Sis Ferrule 4mm Alloy (Bottle of 100)','30.45','Parts');
INSERT INTO expenses VALUES('26-Aug-14','Amazon','1','Jagwire 4mm Derailleur Housing w/ L3 Liner, Roll/25 Black','25.55','Parts');
INSERT INTO expenses VALUES('26-Aug-14','Amazon','1','Clarks Brake Housing Ferrule (Silver, 5-mm)','17.51','Parts');
INSERT INTO expenses VALUES('26-Aug-14','Amazon','1','Pyramid Lined Cable Housing 50 ft. Roll','16.66','Parts');
INSERT INTO expenses VALUES('26-Aug-14','Amazon','1','Clarks Universal Cable Ends (1.0 - 1.6-mm)','16.25','Parts');
INSERT INTO expenses VALUES('26-Aug-14','Amazon','1','MA Tax','1.9','Tax');
INSERT INTO expenses VALUES('26-Aug-14','Amazon','1','MA Tax','1.09','Tax');
INSERT INTO expenses VALUES('26-Aug-14','Amazon','1','10 Pcs 1.77M Length Bike Replaceable Cycling Rear Brake Cable (Returned)','7.85','Parts');
INSERT INTO expenses VALUES('26-Aug-14','Amazon','1','Gift Card','-14.61','Refund');
INSERT INTO expenses VALUES('26-Aug-14','Amazon','1','Gift Card','-16.25','Refund');
INSERT INTO expenses VALUES('29-Aug-14','Amazon','1','Shimano Zinc Shift Cable Box of 10 (1.2x2100mm)','13.99','Parts');
INSERT INTO expenses VALUES('29-Aug-14','Amazon','1','10 PCS 180CM Road Bike Bicycle Brake Inner Wire Cable for Shimano Sram Avid','12.99','Parts');
INSERT INTO expenses VALUES('14-Sep-14','Ace Wheelworks','1','Cleats ATB Shimano SH51 SPD','19.99','Clothing');
INSERT INTO expenses VALUES('14-Sep-14','Ace Wheelworks','3','CO2 Cartridge 16g Threaded','8.97','Parts');
INSERT INTO expenses VALUES('14-Sep-14','Ace Wheelworks','1','MA Tax','-1.88','Tax');
INSERT INTO expenses VALUES('14-Sep-14','Ace Wheelworks','1','C-Ring Shimano 5750 10S 50T','-58.99','Parts');
INSERT INTO expenses VALUES('22-Sep-14','Amazon','1','Shimano SM-CB70 Brake cable Adjuster (5-mm)','19.42','Parts');
INSERT INTO expenses VALUES('22-Sep-14','Amazon','1','MA Tax','1.21','Tax');
INSERT INTO expenses VALUES('27-Sep-14','Amazon','1','10 Pcs 1.77M Length Bike Replaceable Cycling Rear Brake Cable (Returned)','-7.85','Parts');
INSERT INTO expenses VALUES('13-Oct-14','Cambridge Bicycle','1','Planet Bike Blinky 7 Red LED','17.96','Accessories');
INSERT INTO expenses VALUES('13-Oct-14','Cambridge Bicycle','1','MA Tax','1.12','Tax');
INSERT INTO expenses VALUES('18-Nov-14','Cambridge Bicycle','1','Serfas True Li-Ion Battery','40','Accessories');
INSERT INTO expenses VALUES('18-Nov-14','Cambridge Bicycle','1','Giro Merio Wool Winter Sock XL','20','Clothing');
INSERT INTO expenses VALUES('18-Nov-14','Cambridge Bicycle','1','MA Tax','1.25','Tax');
INSERT INTO expenses VALUES('28-Nov-14','CLUG','2','CLUG 2 for 1','12.5','Accessories');
INSERT INTO expenses VALUES('28-Nov-14','CLUG','1','MA Tax','0.62','Tax');
INSERT INTO expenses VALUES('12-Dec-14','Cambridge Bicycle','1','Pedro''s Chainj Lubricant 4oz','8.95','Parts');
INSERT INTO expenses VALUES('12-Dec-14','Cambridge Bicycle','1','MA Tax','0.56','Tax');
INSERT INTO expenses VALUES('16-Dec-14','Cambridge Bicycle','1','Velocity Dyad 700c 36H Silver Rim','70','Parts');
INSERT INTO expenses VALUES('16-Dec-14','Cambridge Bicycle','32','Butted Spokes','56','Parts');
INSERT INTO expenses VALUES('16-Dec-14','Cambridge Bicycle','1','HUB Rear Shimano FH-400 Tiagra 36H 8/9 sp','46','Parts');
INSERT INTO expenses VALUES('16-Dec-14','Cambridge Bicycle','1','Labor Wheel Build','35','Labor');
INSERT INTO expenses VALUES('16-Dec-14','Cambridge Bicycle','1','MA Tax','10.75','Tax');
INSERT INTO expenses VALUES('5-Jan-15','Cambridge Bicycle','1','MA Tax','5.12','Tax');
INSERT INTO expenses VALUES('15-Jan-15','Cambridge Bicycle','1','Continental Grand Prix 4-Season 700x23','74.95','Parts');
INSERT INTO expenses VALUES('15-Jan-15','Cambridge Bicycle','1','700x18-23 60mm PV Tube','6.99','Parts');
INSERT INTO expenses VALUES('21-Mar-15','Amazon','1','Sony 3V Lithium CR2032 Batteries (4 Blisters of 5), 20 Cells','7.3','Accessories');
INSERT INTO expenses VALUES('21-Mar-15','Amazon','1','Points','-7.3','Refund');
INSERT INTO expenses VALUES('24-Mar-15','Cambridge Bicycle','1','Kool Stop V-Brake Pad Inserts','11.95','Parts');
INSERT INTO expenses VALUES('24-Mar-15','Cambridge Bicycle','1','MA Tax','0.75','Tax');
INSERT INTO expenses VALUES('2-Apr-15','CycleGarb.com','2','Castelli Velocissimo Due_ L12007-010','140.23','Clothing');
INSERT INTO expenses VALUES('14-May-15','Hammerhead','1','Hammerhead 1.0','68','Accessories');
INSERT INTO expenses VALUES('14-May-15','Cambridge Bicycle','1','MA Tax','0.62','Tax');
INSERT INTO expenses VALUES('8-Jun-15','Belmont Wheelworks','1','Saddle MNS Specialized Toupe Expert','116.99','Parts');
INSERT INTO expenses VALUES('8-Jun-15','Belmont Wheelworks','1','Headlight Serfas True 500S','89.99','Accessories');
INSERT INTO expenses VALUES('8-Jun-15','Belmont Wheelworks','1','Taillight Planet Bike Super USB','31.49','Accessories');
INSERT INTO expenses VALUES('8-Jun-15','Belmont Wheelworks','1','Front Light Nite Bug 3.0','17.99','Accessories');
INSERT INTO expenses VALUES('8-Jun-15','Belmont Wheelworks','1','MA Tax','17.94','Tax');
INSERT INTO expenses VALUES('8-Jun-15','Belmont Wheelworks','1','Mirror Takealook Eyeglass','13.49','Accessories');
INSERT INTO expenses VALUES('8-Jun-15','Belmont Wheelworks','1','Taillight Serfas TL-Helmet','10.79','Accessories');
INSERT INTO expenses VALUES('8-Jun-15','Belmont Wheelworks','1','Mount Planet Bike Taillight Rack','6.29','Accessories');
INSERT INTO expenses VALUES('12-Jun-15','Cambridge Bicycle','1','Continental Grand Prix 4-Season 700x25','63.71','Parts');
INSERT INTO expenses VALUES('12-Jun-15','Cambridge Bicycle','1','700 x 18-2332mm  PV Tube','6.99','Parts');
INSERT INTO expenses VALUES('12-Jun-15','Cambridge Bicycle','1','MA Tax','4.42','Tax');
INSERT INTO expenses VALUES('16-Jun-15','Cambridge Bicycle','1','Planet Bike Speed EZ Freddy Fenders','44.95','Accessories');
INSERT INTO expenses VALUES('16-Jun-15','Cambridge Bicycle','1','MA Tax','2.81','Tax');
INSERT INTO expenses VALUES('17-Jun-15','Landry''s Bicycles','2','Specialized Hybrid Tube 700 x 18-23 ','17.98','Parts');
INSERT INTO expenses VALUES('17-Jun-15','Landry''s Bicycles','1','MA Tax','1.12','Tax');
INSERT INTO expenses VALUES('27-Jul-15','Amazon','1','3V Lithium Button Cell Batteries CR2450, 20 Cells','11.99','Accessories');
INSERT INTO expenses VALUES('27-Jul-15','Amazon','1','Park Tool Pump Rebuild Kit for PFP-3','6.99','Tools');
INSERT INTO expenses VALUES('8-Aug-15','Notini Sri','1','RUDY PROJECT RYDON Carbon - SN790914','127.12','Clothing');
INSERT INTO expenses VALUES('25-Aug-15','Harris Cyclery','1','TA 110x52 Outer Chainring CRT212 CG','81.95','Parts');
INSERT INTO expenses VALUES('25-Aug-15','Harris Cyclery','1','9sp 11-28 HG80 Shimano Cassette CG','69.95','Parts');
INSERT INTO expenses VALUES('25-Aug-15','Harris Cyclery','1','TA 110x39 Middle Chairing CRT139 CG','64.95','Parts');
INSERT INTO expenses VALUES('25-Aug-15','Harris Cyclery','1','SRAM PC971 9 spd Chain CH1083 CG','29.95','Parts');
INSERT INTO expenses VALUES('25-Aug-15','Harris Cyclery','1','MA Tax','15.43','Tax');
INSERT INTO expenses VALUES('3-Sep-15','Ferris Wheels','1','Continental Folding Clincher Grand Prix 4000-S II 700x25','69.9','Parts');
INSERT INTO expenses VALUES('3-Sep-15','Ferris Wheels','1','Pedro''s Green Fizz 16oz','10.91','Parts');
INSERT INTO expenses VALUES('3-Sep-15','Ferris Wheels','1','QTubes 700c x 23-25m 32mm PV 125g TU6878','6.59','Parts');
INSERT INTO expenses VALUES('3-Sep-15','Ferris Wheels','1','MA Tax','5.46','Tax');
INSERT INTO expenses VALUES('4-Sep-15','Ebay-DiscountBicycle603','1','Shimano Claris 2400 Triple Left STI Lever','46.8','Parts');
INSERT INTO expenses VALUES('4-Sep-15','Ebay-DiscountBicycle603','1','Shipping','5.95','Shipping');
INSERT INTO expenses VALUES('23-Sep-15','Amazon','1','HotHands Toe Warmers (40 pairs)','35.37','Accessories');
INSERT INTO expenses VALUES('23-Sep-15','Amazon','1','Pearl Izumi - Ride Elite Thermal Wool Socks, Large, Black','20','Clothing');
INSERT INTO expenses VALUES('23-Sep-15','Amazon','1','DeFeet Men''s Woolie Boolie 6-Inch Sock, Charcoal, Large','15.89','Clothing');
INSERT INTO expenses VALUES('6-Nov-15','Cambridge Bicycle','1','Continental Grand Prix 4-Season 700x25','74.95','Parts');
INSERT INTO expenses VALUES('6-Nov-15','Cambridge Bicycle','1','MA Tax','4.68','Tax');
INSERT INTO expenses VALUES('30-Nov-15','Amazon','1','Maxell CR2032 lithium batteries -Pack of 15 "NEW HOLOGRAM PACKAGE"','7.45','Accessories');
INSERT INTO expenses VALUES('30-Nov-15','Amazon','1','Points','-7.45','Refund');
INSERT INTO expenses VALUES('16-Dec-15','Amazon','1','10pcs Panasonic Cr2450 3v Coin Lithium Battery','14.99','Accessories');
INSERT INTO expenses VALUES('26-Feb-16','Cambridge Bicycle','1','Kool Stop V-Brake Pad Inserts','9.95','Parts');
INSERT INTO expenses VALUES('26-Feb-16','Cambridge Bicycle','1','MA Tax','0.62','Tax');
INSERT INTO expenses VALUES('3-Mar-16','MAPFRE Insurance','1','Mount Planet Bike Taillight Rack','-6.29','Insurance');
INSERT INTO expenses VALUES('3-Mar-16','MAPFRE Insurance','1','MA Tax','-9.67','Insurance');
INSERT INTO expenses VALUES('3-Mar-16','MAPFRE Insurance','1','Taillight Planet Bike Super USB','-31.49','Insurance');
INSERT INTO expenses VALUES('3-Mar-16','MAPFRE Insurance','1','Saddle MNS Specialized Toupe Expert','-116.99','Insurance');
INSERT INTO expenses VALUES('13-May-16','Amazon','1','KMC X9.93 Bicycle Chain (9-Speed, 1/2 x 11/128-Inch, 116L, Silver/Black)','13.88','Parts');
INSERT INTO expenses VALUES('13-May-16','Amazon','1','Park Tool Master Link Pliers','14.36','Tools');
INSERT INTO expenses VALUES('13-May-16','Amazon','1','Shimano Zinc Shift Cable Box of 10 (1.2x2100mm)','14.45','Parts');
INSERT INTO expenses VALUES('13-May-16','Amazon','1','TOOL CHAIN CLEANER PARK CM-5.2 CYCLONE','23.84','Tools');
INSERT INTO expenses VALUES('13-May-16','Amazon','1','Finish Line Gear Floss Microfiber Cleaning Rope (Pack of 20 microfiber ropes)','7.05','Tools');
INSERT INTO expenses VALUES('13-May-16','Amazon','1','Simple Green 18203 Heavy Duty Cleaner and Degreaser, 1 Gallon Bottle','18.43','Tools');
INSERT INTO expenses VALUES('13-May-16','Amazon','1','KMC Missing Link Bicycle Chain Link (9-speed, 6 Pairs)','6.99','Parts');
INSERT INTO expenses VALUES('13-May-16','Amazon','2','2 of Lerway Aluminium Jockey Wheel Rear Derailleur Pulley SHIMANO SRAM 11T 1pcs (Gold)','18.98','Parts');
INSERT INTO expenses VALUES('13-May-16','Amazon','1','Points','-9.52','Refund');
INSERT INTO expenses VALUES('13-May-16','Amazon','1','MA Tax','2.46','Tax');
INSERT INTO expenses VALUES('13-May-16','Amazon','1','Shimano CS-HG50 Hyperglide Cassette (11-25T 9 Speed)','24.72','Parts');
INSERT INTO expenses VALUES('13-May-16','Amazon','1','Points','-24.72','Refund');
INSERT INTO expenses VALUES('13-May-16','Amazon','1','2 pcs Titanium Ti Jockey wheel bolts for Rear Derailleur Pulley Shimano SRAM','5.99','Parts');
INSERT INTO expenses VALUES('13-May-16','Tweeks Cycles','1','TA Zephyr 110 Chainrings Outer 110 52T Silver','46.07','Parts');
INSERT INTO expenses VALUES('13-May-16','Tweeks Cycles','1','Shipping','2.39','Shipping');
INSERT INTO expenses VALUES('13-May-16','Amazon','1','Points','-5.99','Refund');
INSERT INTO expenses VALUES('16-May-16','Ferris Wheels','1','700x23-25 PV48mm Bulk Q-Tube','5.65','Parts');
INSERT INTO expenses VALUES('16-May-16','Ferris Wheels','1','MA Tax','0.35','Tax');
